trigger:
  branches: { include: [ master ] }
  paths:    { include: [ infrastructure/**, scripts/**, azure-pipelines.yml ] }
pr: none

pool: { name: SelfHosted }

stages:
- stage: Validate
  jobs:
  - job: validate
    steps:
    - checkout: self
    - task: AzureCLI@2
      displayName: Validate
      inputs:
        azureSubscription: 'azure-rm-sc'
        scriptType: bash
        addSpnToEnvironment: true
        scriptLocation: scriptPath
        scriptPath: scripts/tf_validate.sh

- stage: Plan
  dependsOn: Validate
  jobs:
  - job: plan
    steps:
    - checkout: self
    - task: AzureCLI@2
      displayName: Plan
      inputs:
        azureSubscription: 'azure-rm-sc'
        scriptType: bash
        addSpnToEnvironment: true
        scriptLocation: scriptPath
        scriptPath: scripts/tf_plan.sh
    - publish: infrastructure/tfplan
      artifact: tfplan

- stage: Apply
  dependsOn: Plan
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: apply
    steps:
    - checkout: self
    - download: current
      artifact: tfplan
    - task: AzureCLI@2
      displayName: Apply
      inputs:
        azureSubscription: 'azure-rm-sc'
        scriptType: bash
        addSpnToEnvironment: true
        scriptLocation: scriptPath
        scriptPath: scripts/tf_apply.sh
